name: SimpleCalculator
options:
  bundleIdPrefix: com.example
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "15.0"
settings:
  DEVELOPMENT_TEAM: ""
targets:
  SimpleCalculator:
    type: application
    platform: iOS
    sources: 
      - path: Sources
        excludes: ["Info.plist"]
    settings:
      INFOPLIST_FILE: Sources/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.example.SimpleCalculator
    scheme:
      testTargets: []
